### ISSUE TITLE
How to use BPT with a custom dataset for a machine translation task?

### ISSUE THREAD

**Issue by nashid** [yzh119/BPT#3]
Thanks for this great artefact. I am interested to apply this library for a machine translation task. However, in my case, I have to feed a custom dataset. Furthermore, I have to add customized nodes and edges as my task is slightly different.

Do you think it is possible with BPT? Would be great if I can discuss this with you in greater detail.

**Comment by yzh119** [comment]
Hi, you can try constructing graphs and writing your transformer structures on top of [DGL](https://docs.dgl.ai/), and [here](https://gist.github.com/yzh119/cc1ab6ad284af8b219bc94568c2f37e6) is an example of how to build a Transformer layer on a customized graph structure.

Regarding BPT itself, actually, it has been three years since I last worked on related projects and I have shifted my research interest after that. The codebase itself is outdated with many old dependencies, I don't recommend you use it directly.

**Comment by nashid** [comment]
got it. Thanks for the feedback.
