### ISSUE TITLE
Publication/Peer Review?

### ISSUE THREAD

**Issue by thesofakillers** [yzh119/BPT#4]
Hi cool work!

Do you have any plans to publish it under peer-review? I was only able to find a preprint version.

Thanks!

**Comment by yzh119** [comment]
Hi, thanks for your attention, this paper was submitted once in 2019 and got desk rejected by ACL 2020 because the time we posted it to ArXiv was a few hours later than the anonymous period.

We didn't attempt to submit it since then because there are a lot of papers working in this direction, and BP-Transformer is only one of the variants.

I'm glad that BP-Transformer inspires some of the influential works.
